version: '3.7'

networks:
  spark_network:
    driver: bridge

services:
  spark-master:
    build:
      context: docker/
      dockerfile: Dockerfile.spark
    container_name: sparkMaster
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no 
      - SPARK_RPC_ENCRYPTION_ENABLED=no 
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - spark_network
    # volumes:
    #   - 
  
  spark-worker:
    build: 
      context: docker/
      dockerfile: Dockerfile.spark
    container_name: sparkWorker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no 
      - SPARK_RPC_ENCRYPTION_ENABLED=no 
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8081:8081"
    networks:
      - spark_network
    # volumes:
    #   -
    depends_on:
      - spark-master