FROM bitnami/spark

RUN curl https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/3.1.0/kafka-clients-3.1.0.jar --output /opt/bitnami/spark/jars/kafka-clients-3.1.0.jar && \
    curl https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.3.0/spark-sql-kafka-0-10_2.12-3.3.0.jar --output /opt/bitnami/spark/jars/spark-sql-kafka-0-10_2.12-3.3.0.jar && \
    curl https://repo1.maven.org/maven2/org/apache/spark/spark-streaming-kafka-0-10_2.12/3.3.0/spark-streaming-kafka-0-10_2.12-3.3.0.jar --output /opt/bitnami/spark/jars/spark-streaming-kafka-0-10_2.12-3.3.0.jar && \
    curl https://repo1.maven.org/maven2/org/apache/commons/commons-pool2/2.11.0/commons-pool2-2.11.0.jar --output /opt/bitnami/spark/jars/commons-pool2-2.11.0.jar && \
    curl https://repo1.maven.org/maven2/org/apache/spark/spark-token-provider-kafka-0-10_2.12/3.3.0/spark-token-provider-kafka-0-10_2.12-3.3.0.jar --output /opt/bitnami/spark/jars/spark-token-provider-kafka-0-10_2.12-3.3.0.jar && \
    curl https://repo1.maven.org/maven2/org/spark-project/spark/unused/1.0.0/unused-1.0.0.jar --output /opt/bitnami/spark/jars/unused-1.0.0.jar && \
    curl https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.jar --output /opt/bitnami/spark/jars/hadoop-aws-3.3.4.jar && \
    curl https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-s3/1.12.319/aws-java-sdk-s3-1.12.319.jar --output /opt/bitnami/spark/jars/aws-java-sdk-s3-1.12.319.jar && \
    curl https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-core/1.12.319/aws-java-sdk-core-1.12.319.jar --output /opt/bitnami/spark/jars/aws-java-sdk-core-1.12.319.jar && \
    curl https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk/1.12.319/aws-java-sdk-1.12.319.jar --output /opt/bitnami/spark/jars/aws-java-sdk-1.12.319.jar && \
    curl https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-client/3.3.4/hadoop-client-3.3.4.jar --output /opt/bitnami/spark/jars/hadoop-client-3.3.4.jar && \
    curl https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-common/3.3.4/hadoop-common-3.3.4.jar --output /opt/bitnami/spark/jars/hadoop-common-3.3.4.jar