FROM bitnami/spark

RUN curl https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/3.1.0/kafka-clients-3.1.0.jar --output /opt/bitnami/spark/jars/kafka-clients-3.1.0.jar && \
    curl https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.3.0/spark-sql-kafka-0-10_2.12-3.3.0.jar --output /opt/bitnami/spark/jars/spark-sql-kafka-0-10_2.12-3.3.0.jar && \
    curl https://repo1.maven.org/maven2/org/apache/spark/spark-streaming-kafka-0-10_2.12/3.3.0/spark-streaming-kafka-0-10_2.12-3.3.0.jar --output /opt/bitnami/spark/jars/spark-streaming-kafka-0-10_2.12-3.3.0.jar && \
    curl https://repo1.maven.org/maven2/org/apache/commons/commons-pool2/2.11.0/commons-pool2-2.11.0.jar --output /opt/bitnami/spark/jars/commons-pool2-2.11.0.jar && \
    curl https://repo1.maven.org/maven2/org/apache/spark/spark-token-provider-kafka-0-10_2.12/3.3.0/spark-token-provider-kafka-0-10_2.12-3.3.0.jar --output /opt/bitnami/spark/jars/spark-token-provider-kafka-0-10_2.12-3.3.0.jar && \
    curl https://repo1.maven.org/maven2/org/spark-project/spark/unused/1.0.0/unused-1.0.0.jar --output /opt/bitnami/spark/jars/unused-1.0.0.jar